---
- name: ubuntu trusty
  when: >
    ansible_distribution == 'Ubuntu'
    and ansible_distribution_version == '14.04'
  block:
  - name: byobu ppa
    apt_repository:
      repo: 'ppa:byobu/ppa'

- name: byobu
  apt:
    name: byobu
    state: latest

- file:
    path: /usr/bin/purge-old-kernels
    state: file

- name: crontab
  copy:
    content: |
      #! /bin/bash

      /usr/bin/purge-old-kernels -y {{ pok_keep if pok_keep is not none else '' }}

    dest: /etc/cron.daily/purge-old-kernels
    owner: root
    group: root
    mode: u=rwx,g=rx,o=r
