---
- hosts: all
  remote_user: root
  vars_files:
    - vars/powo.yml
    - [ "vars/first-run.yml", "vars/empty.yml" ]
    - [ "vars/env.yml", "vars/empty.yml" ]
  roles:
    # modules
    - paluh.augeas
    # configurations
    - base
    - system
    - base_user
    - tools
    - desktop
  environment: "{{ env_vars|default({}) }}"
