---
- hosts: all
  remote_user: root
  vars_files:
    - vars/powo.yml
    - [ "vars/first-run.yml", "vars/empty.yml" ]
    - [ "vars/env.yml", "vars/empty.yml" ]
  roles:
    # modules
    - paluh.augeas
    - role: cchurch.virtualenv
      virtualenv_path: /usr/local/powo/virtualenv
      virtualenv_requirements: /etc/powo/requirements.txt
    # configurations
    - base
    - system
    - base_user
    - tools
    - desktop
  environment: "{{ env_vars|default({}) }}"
