---
- hosts: all
  remote_user: root
  become: true
  become_method: sudo
  become_user: root
  vars_files:
    - vars/powo.yml
    - [ "vars/first-run.yml", "vars/empty.yml" ]
    - [ "vars/env.yml", "vars/empty.yml" ]
  roles:
    - role: purge-old-kernels
      pok_keep: "{{ playbook_pok_keep | default(None) }}"
      when: ansible_distribution == 'Ubuntu'
  environment: "{{ env_vars|default({}) }}"
