- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"

- name: apt-get update
  apt:
    update_cache: yes
  when: ansible_distribution == 'Ubuntu'

- include: python-package.yml
- include: fedora-cloud-workaround.yml

- name: libaugeas install
  package: pkg={{ item }}
  with_items: "{{ packages.augeas }}"
