- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"

- name: apt-get update
  apt:
    update_cache: yes
  when: ansible_distribution == 'Ubuntu'

- name: libaugeas install
  package: pkg={{ item }}
  with_items: "{{ packages.augeas }}"

- include: python-package.yml
- include: fedora-cloud-workaround.yml

# Disabled as it requires some prerequisites about partitionning
#- include: switch_home_data.yml
#  when: modules.home_data_switch.enabled
