- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"

- include: cinnamon.yml
  when: desktop.cinnamon.enabled

- include: gnome-desktop.yml
  when: desktop.cinnamon.enabled

- name: lightdm install
  package: pkg=lightdm
