- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"

- include: dm.yml

- include: cinnamon.yml
  when: modules.cinnamon.enabled | default(False)

- include: gnome-desktop.yml
  when: modules.gnome.enabled | default(False)
