---
- name: check apparmor
  shell: >
    which apparmor_status
    && apparmor_status
  register: apparmor_is_enabled
  ignore_errors: yes
  changed_when: no

- name: disable apparmor
  shell: >
    invoke-rc.d apparmor teardown
    && update-rc.d -f apparmor remove
  when: apparmor_is_enabled|success
