- name: backports trusty
  package:
    pkg:
      - linux-generic-lts-xenial
      - xserver-xorg-core-lts-xenial
      - xserver-xorg-lts-xenial
      - xserver-xorg-video-all-lts-xenial
      - xserver-xorg-input-all-lts-xenial
      - libwayland-egl1-mesa-lts-xenial
  when: ansible_distribution_release == 'trusty'

- name: backports xenial
  apt:
    name: "{{ item }}"
    install_recommends: yes
  with_items:
    - linux-generic-hwe-16.04
    - xserver-xorg-hwe-16.04
  when: ansible_distribution_release == 'xenial'
