- include_vars: "common.yml"

- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"

- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}_{{ ansible_distribution_release }}.yml"
    - default.yml

- name: 70-persistent-net.rules delete
  file: path=/etc/udev/rules.d/70-persistent-net.rules state=absent

- include: backports.yml
  when: modules.backports.enabled | default(False)
- include: apparmor_disabled.yml
  when: modules.disable_security.enabled | default(False) and ansible_distribution == 'Ubuntu'
- include: selinux_disabled.yml
  when: modules.disable_security.enabled | default(False) and ansible_distribution == 'Fedora'
- include: mountpoints.yml
  when: modules.mountpoints.enabled | default(False)
- include: data_services.yml
  when: modules.data_services.enabled | default(False)
- include: mysql.yml
  when: modules.mysql.enabled | default(False)
- include: postgresql.yml
  when: modules.postgresql.enabled | default(False)
- include: apache.yml
  when: modules.apache.enabled | default(False)
- include: openssh.yml
  when: modules.openssh.enabled | default(False)

- name: misc servers
  package: pkg={{ item }}
  with_items:
    - memcached
  when: modules.memcached.enabled | default(False)

