- name: openssh install
  package: pkg={{ item }}
  with_items: "{{ openssh.packages }}"

- name: openssh PermitRootLogin=yes
  augeas:
    command: set
    path: /files/etc/ssh/sshd_config/PermitRootLogin
    # quotes needed to disable boolean cast
    value: "yes"

- name: openssh enables ssh-dss
  augeas:
    command: set
    path: /files/etc/ssh/sshd_config/PubkeyAcceptedKeyTypes
    value: "+ssh-dss"


