- name: cinnamon repository
  apt_repository:
    repo: ppa:tsvetko.tsvetkov/cinnamon
    validate_certs: "{{ common.validate_ssl_certs }}"

- name: cinnamon installation
  package: pkg={{ item }}
  with_items:
    - cinnamon
    - python-lxml
    - gir1.2-gnomedesktop-3.0
    - gnome-icon-theme
    - gnome-icon-theme-extras
    - gnome-icon-theme-full
  when: "{{ desktop.cinnamon.enabled }}"

- include: ../include/gsettings.yml
  vars:
    schema: "{{ item.schema }}"
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items: "{{ desktop.gsettings }}"
  become: yes
  become_user: "{{ powo_user }}"

- name: calendar settings folder
  file:
    path: "{{ powo_home }}/.cinnamon/configs/calendar@cinnamon.org"
    state: directory
    mode: ugo+rwx
    owner: "{{ powo_user }}"
    group: "{{ powo_user }}"

- name: calendar settings
  copy:
    dest: "{{ powo_home }}/.cinnamon/configs/calendar@cinnamon.org/calendar@cinnamon.org.json"
    src: ../files/calendar@cinnamon.org.json
    force: yes
    mode: ugo+rwx
    owner: "{{ powo_user }}"
    group: "{{ powo_user }}"
