powo_password: "{{ lookup('env', 'POWO_PASSWORD') }}"
powo_passphrase: "{{ lookup('env', 'POWO_PASSPHRASE') }}"

common:
    validate_ssl_certs: true

desktop:
    cinnamon:
        enabled: false
    gnome:
        enabled: false

eclipse:
    distributions:
        owsi-4.5-x86_64:
            target_filename: eclipse-4.5-x86_64.tar.gz
            target_directory: eclipse-4.5-x86_64
            url: __DOWNLOAD_URL__
            checksum: __CHECKSUM__
            desktop_name: Eclipse 4.5

jdk:
    distributions:
        1.7.71-x86_64:
            target_filename: jdk-7u71-linux-x86_64.tar.gz
            target_directory: jdk-1.7.71-x86_64
            url: __DOWNLOAD_URL__
            checksum: md5:22761b214b1505f1a9671b124b0f44f4

maven:
    distributions:
        3.2.1:
            target_filename: apache-maven-3.2.1-bin.tar.gz
            target_directory: apache-maven-3.2.1
            url: __DOWNLOAD_URL__
            checksum: md5:aaef971206104e04e21a3b580d9634fe

tomcat:
    distributions:
        7.0.53:
            target_filename: apache-tomcat-7.0.53.tar.gz
            target_directory: apache-tomcat-7.0.53
            url: __DOWNLOAD_URL__
            checksum: md5:7062e134b4390e2ce6b54081aab26e3c

remote:
    client_hostname: "{{ powo_user }}"
