- block:
  - name: bashrc.d directory
    file:
      path: "{{ powo_home }}/.bashrc.d"
      owner: "{{ powo_user }}"
      group: "{{ powo_group }}"
      mode: u=rwx,g=rwx,o=rx
      state: directory
  
  - name: bashrc.d loading
    blockinfile:
      create: false
      dest: "{{ powo_home }}/.bashrc"
      owner: "{{ powo_user }}"
      group: "{{ powo_group }}"
      mode: u=rw,g=rw,o=r
      state: present
      insertafter: EOF
      block: |
          if [ -d "$HOME/.bashrc.d" -a $( find "$HOME/.bashrc.d" -type f -name "*.conf" | wc -l ) -ne 0 ]; then
              . $HOME/.bashrc.d/*.conf
          fi
  
  - name: bash_profile.d directory
    file:
      path: "{{ powo_home }}/.bash_profile.d"
      owner: "{{ powo_user }}"
      group: "{{ powo_group }}"
      mode: u=rwx,g=rwx,o=rx
      state: directory
  
  - name: bash_profile.d loading
    blockinfile:
      create: yes
      dest: "{{ powo_home }}/.bash_profile"
      owner: "{{ powo_user }}"
      group: "{{ powo_group }}"
      mode: u=rw,g=rw,o=r
      state: present
      insertafter: EOF
      block: |
          if [ -d "$HOME/.bash_profile.d" -a $( find "$HOME/.bash_profile.d" -type f -name "*.conf" | wc -l ) -ne 0 ]; then
              . $HOME/.bash_profile.d/*.conf
          fi
  
  - name: bash_profile.d/powo.conf
    template:
      dest: "{{ powo_home }}/.bash_profile.d/powo.conf"
      force: yes
      owner: "{{ powo_user }}"
      group: "{{ powo_group }}"
      mode: u=rw,g=rw,o=r
      src: ../files/bash_profile.d_powo.conf.jinja
  
  when: modules.bash_config.enabled | default(False)
  become_user: "{{ powo_user }}"
