- block:
  - name: "{{ powo_user }} user creation"
    user:
        name: "{{ powo_user }}"
        shell: /bin/bash
        groups: "{{ user.groups }}"
        append: yes
        comment: "{{ powo_fullname }}"
        createhome: yes
        password: "{{ powo_password }}"
        update_password: on_create

  - block:
    - name: ".ssh folder"
      file:
        path: "{{ powo_home }}/.ssh"
        state: directory
        owner: "{{ powo_user }}"
        group: "{{ powo_group }}"
        mode: u=rwx,g=,o=

    - name: .ssh/id_rsa check
      file:
        path: "{{ powo_home }}/.ssh/id_rsa"
        state: file
      ignore_errors: yes
      register: id_rsa_exists

    - name: .ssh/id_rsa creation
      command: ssh-keygen -t rsa -f "{{ powo_home }}/.ssh/id_rsa" -N "{{ powo_passphrase }}"
      when: >
        id_rsa_exists | failed
        and powo_passphrase | trim | default(None)

    - name: .ssh/id_rsa not generated"
      debug:
        msg: .ssh/id_rsa cannot be provided because no powo_passphrase was provided
      when: >
        id_rsa_exists | failed
        and not powo_passphrase | trim | default(None)

    when: modules.user.keygen.enabled | default(False)
    become_user: "{{ powo_user }}"

  - block:
    - name: check home symlink
      file:
        path: /home
        state: link
        src: /data/home
      ignore_errors: yes
      register: home_link

    - name: home move
      command: mv -t /data /home
      when: "{{ home_link.state == 'directory' }}"

    - name: home symlink
      file:
        path: /home
        state: link
        src: /data/home

    when: modules.user.switch_home.enabled | default(False)

  when: modules.user.enabled | default(False)
