- name: mysql
  package: pkg={{ item }}
  with_items: "{{ mysql.packages }}"

- name: "{{ mysql.data_dir }} symlink"
  file:
      path: "{{ mysql.data_dir }}"
      state: link
      src: "{{ mysql.data_services_dir }}"
  ignore_errors: true
  register: var_mysql_link

- block:
    - name: stopping mysql
      service: name={{ mysql.service }} state=stopped

    - name: checking {{ mysql.data_services_dir }}
      stat: path={{ mysql.data_services_dir }}
      register: data_mysql

    - name: backup existing {{ mysql.data_services_dir }}
      command: mv {{ mysql.data_services_dir }} {{ mysql.data_services_dir }}.back
      when: "{{ data_mysql.stat.exists }}"

    - name: moving {{ mysql.data_dir }} to {{ mysql.data_services_dir }}
      shell: mv -t $( dirname "{{ mysql.data_services_dir }}" ) {{ mysql.data_dir }}

  when: "{{ var_mysql_link.state == 'directory' }}"

- name: "{{ mysql.data_dir }} symlink"
  file:
      path: "{{ mysql.data_dir }}"
      state: link
      src: "{{ mysql.data_services_dir }}"

- name: starting mysql
  service: name={{ mysql.service }} state=started
