- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"

- name: eclipse libwebkitgtk
  package:
    name: "{{ item }}"
    state: installed
  with_items: "{{ eclipse.libwebkitgtk }}"

- include: eclipse_item.yml
  with_dict: "{{ eclipse.distributions }}"
  when:
    - modules.eclipse.enabled | default(False)
    - item.value.enabled | default(False)

- include: eclipse_link.yml
  when: modules.eclipse.enabled | default(False)

- include: jdk_item.yml
  with_dict: "{{ jdk.distributions }}"
  when:
    - modules.jdk.enabled | default(False)
    - item.value.enabled | default(False)

- include: jdk_link.yml
  when: modules.jdk.enabled | default(False)

- include: maven_item.yml
  with_dict: "{{ maven.distributions }}"
  when:
    - modules.maven.enabled | default(False)
    - item.value.enabled | default(False)

- include: maven_link.yml
  when: modules.maven.enabled | default(False)

- include: maven_settings.yml
  when: modules.maven.settings.enabled | default(False)

- include: tomcat_item.yml
  with_dict: "{{ tomcat.distributions }}"
  when:
    - modules.tomcat.enabled | default(False)
    - item.value.enabled | default(False)

- include: tomcat_link.yml
  when: modules.tomcat.enabled | default(False)

- include: virtualbox.yml
  when: modules.virtualbox.enabled | default(False)
- include: chrome.yml
  when: modules.chrome.enabled | default(False)
- include: misc.yml
  when: modules.misc.enabled | default(False)
