- include_vars: maven_item_vars.yml

- name: prepare tools folder
  file:
    path: "{{ archive_destination_folder }}"
    state: directory
    mode: u=rwx,g=rwx,o=rx
    owner: "{{ powo_user }}"
    group: "{{ powo_user }}"

- name: prepare apps folder
  file:
    path: "{{ install_destination }}"
    state: directory
    mode: u=rwx,g=rwx,o=rx
    owner: "{{ powo_user }}"
    group: "{{ powo_user }}"

- name: download maven
  get_url:
    url: "{{ distribution.url }}"
    dest: "{{ archive_destination }}"
    checksum: "{{ distribution.checksum }}"
    validate_certs: "{{ common.validate_ssl_certs }}"
    owner: "{{ powo_user }}"
    group: "{{ powo_user }}"
  become_user: "{{ powo_user }}"

# unarchive does not support tar strip
- name: install maven
  command: tar -xzf "{{ archive_destination }}" -C "{{ install_destination }}" --strip 1
  args:
    creates: "{{ maven_bin_path }}"
  become_user: "{{ powo_user }}"
