- name: tomcat default - {{ tomcat['link'] | default("none") }}
  file:
    path: "{{ powo_home }}/Documents/apps/tomcat"
    state: link
    src: "{{ powo_home }}/Documents/apps/{{ tomcat.distributions[tomcat.link].target_directory }}"
  when: "{{ tomcat.link is defined }}"
  become_user: "{{ powo_user }}"
