modules:
    home_data_switch:
        enabled: false
    user:
        enabled: false
        switch_home:
            enabled: false
        keygen:
            enabled: false
    bash_config:
        enabled: false
    backports:
        enabled: false
    postgresql:
        enabled: false
        security:
            enabled: false
        shared_memory:
            enabled: false
        switch_data:
            enabled: false
    memcached: false
    openssh:
        enabled: false
        root_login:
            enabled: false
        dsa_pub:
            enabled: false
    apache:
        enabled: false
    mysql:
        enabled: false
        switch_data:
            enabled: false
    mountpoints:
        enabled: false
    disable_security:
        enabled: false
    data_services:
        enabled: false
    misc:
        enabled: false
    chrome:
        enabled: false
    virtualbox:
        enabled: false
    tomcat:
        enabled: false
    squirrel:
        enabled: false
    maven:
        enabled: false
        settings:
            enabled: false
    jdk:
        enabled: false
    eclipse:
        enabled: false
    cinnamon:
        enabled: false
    gnome:
        enabled: false

powo_group: "{{ powo_user }}"
powo_password: "{{ lookup('env', 'POWO_PASSWORD') }}"
powo_passphrase: "{{ lookup('env', 'POWO_PASSPHRASE') }}"

common:
    validate_ssl_certs: false

eclipse:
    link: owsi-4.5.2-x86_64
    default_vmargs: "-Xmx1512m"
    distributions:
        owsi-4.5-x86_64:
            target_filename: owsi-eclipse-jee-mars-4.5-linux-gtk-x86_64.tar.gz
            target_directory: owsi-eclipse-jee-mars-4.5-linux-gtk-x86_64
            url: __DOWNLOAD_URL__
            checksum: __CHECKSUM__
            desktop_name: Eclipse 4.5

        owsi-4.5.2-x86_64:
            target_filename: owsi-eclipse-jee-mars-4.5.2-linux-gtk-x86_64.tar.gz
            target_directory: owsi-eclipse-jee-mars-4.5.2-linux-gtk-x86_64
            url: __DOWNLOAD_URL__
            checksum: __CHECKSUM__
            desktop_name: Eclipse 4.5.2

        owsi-4.6-x86_64:
            target_filename: owsi-eclipse-jee-neon-4.6-linux-gtk-x86_64.tar.gz
            target_directory: owsi-eclipse-jee-neon-4.6-linux-gtk-x86_64
            url: __DOWNLOAD_URL__
            checksum: __CHECKSUM__
            desktop_name: Eclipse 4.6
            vm: "{{ powo_home }}/Documents/apps/jdk-1.8.112-x86_64/bin/java"

        owsi-4.6.1-x86_64:
            target_filename: owsi-eclipse-jee-neon-4.6.1-linux-gtk-x86_64.tar.gz
            target_directory: owsi-eclipse-jee-neon-4.6.1-linux-gtk-x86_64
            url: __DOWNLOAD_URL__
            checksum: __CHECKSUM__
            desktop_name: Eclipse 4.6.1
            vm: "{{ powo_home }}/Documents/apps/jdk-1.8.112-x86_64/bin/java"

        owsi-4.6.2-x86_64:
            target_filename: owsi-eclipse-jee-neon-4.6.2-linux-gtk-x86_64.tar.gz
            target_directory: owsi-eclipse-jee-neon-4.6.2-linux-gtk-x86_64
            url: __DOWNLOAD_URL__
            checksum: __CHECKSUM__
            desktop_name: Eclipse 4.6.2
            vm: "{{ powo_home }}/Documents/apps/jdk-1.8.112-x86_64/bin/java"

jdk:
    link: 1.7.71-x86_64
    distributions:
        1.7.71-x86_64:
            target_filename: jdk-7u71-linux-x64.tar.gz
            target_directory: jdk-1.7.71-x86_64
            url: __DOWNLOAD_URL__
            checksum: md5:22761b214b1505f1a9671b124b0f44f4

        1.8.102-x86_64:
            target_filename: jdk-8u102-linux-x64.tar.gz
            target_directory: jdk-1.8.102-x86_64
            url: __DOWNLOAD_URL__
            checksum: md5:bac58dcec9bb85859810a2a6acba740b

        1.8.112-x86_64:
            target_filename: jdk-8u112-linux-x64.tar.gz
            target_directory: jdk-1.8.112-x86_64
            url: __DOWNLOAD_URL__
            checksum: md5:de9b7a90f0f5a13cfcaa3b01451d0337

maven:
    link: 3.3.9
    settings_xml: __DOWNLOAD__URL__
    distributions:
        3.2.1:
            target_filename: apache-maven-3.2.1-bin.tar.gz
            target_directory: apache-maven-3.2.1
            url: __DOWNLOAD_URL__
            checksum: md5:aaef971206104e04e21a3b580d9634fe

        3.3.9:
            target_filename: apache-maven-3.3.9-bin.tar.gz
            target_directory: apache-maven-3.3.9
            url: __DOWNLOAD_URL__
            checksum: md5:516923b3955b6035ba6b0a5b031fbd8b

tomcat:
    link: 7.0.53
    distributions:
        7.0.53:
            target_filename: apache-tomcat-7.0.53.tar.gz
            target_directory: apache-tomcat-7.0.53
            url: __DOWNLOAD_URL__
            checksum: md5:7062e134b4390e2ce6b54081aab26e3c

squirrel:
    link: 3.7.1
    target_filename: squirrelsql-3.7.1-optional.zip
    target_directory: squirrelsql-3.7.1
    url: https://superb-dca2.dl.sourceforge.net/project/squirrel-sql/1-stable/3.7.1-plainzip/squirrelsql-3.7.1-optional.zip
    checksum: sha1:0c3d8034808574c80ea8b8212a53547df30f975a

remote:
    client_hostname: "{{ powo_user }}"
