modules:
    user:
        enabled: true
        switch_home:
            enabled: true
        keygen:
            enabled: true
    bash_config:
        enabled: true
    postgresql:
        enabled: true
        security:
            enabled: true
        shared_memory:
            enabled: true
        switch_data:
            enabled: true
    memcached: true
    openssh:
        enabled: true
        root_login:
            enabled: true
        dsa_pub:
            enabled: true
    apache:
        enabled: true
    mysql:
        enabled: true
        switch_data:
            enabled: true
    mountpoints:
        enabled: true
    disable_security:
        enabled: true
    data_services:
        enabled: true
    misc:
        enabled: true
    chrome:
        enabled: true
    virtualbox:
        enabled: true
    tomcat:
        enabled: true
    maven:
        enabled: true
    jdk:
        enabled: true
    eclipse:
        enabled: true
    cinnamon:
        enabled: true
    gnome:
        enabled: true

powo_password: "{{ lookup('env', 'POWO_PASSWORD') }}"
powo_passphrase: "{{ lookup('env', 'POWO_PASSPHRASE') }}"

common:
    validate_ssl_certs: false

eclipse:
    distributions:
        owsi-4.5-x86_64:
            target_filename: owsi-eclipse-jee-mars-4.5-linux-gtk-x86_64.tar.gz
            target_directory: owsi-eclipse-jee-mars-4.5-linux-gtk-x86_64
            url: __DOWNLOAD_URL__
            checksum: __CHECKSUM__
            desktop_name: Eclipse 4.5

        owsi-4.5.2-x86_64:
            target_filename: owsi-eclipse-jee-mars-4.5.2-linux-gtk-x86_64.tar.gz
            target_directory: owsi-eclipse-jee-mars-4.5.2-linux-gtk-x86_64
            url: __DOWNLOAD_URL__
            checksum: __CHECKSUM__
            desktop_name: Eclipse 4.5.2

jdk:
    distributions:
        1.7.71-x86_64:
            target_filename: jdk-7u71-linux-x64.tar.gz
            target_directory: jdk-1.7.71-x86_64
            url: __DOWNLOAD_URL__
            checksum: md5:22761b214b1505f1a9671b124b0f44f4

maven:
    distributions:
        3.2.1:
            target_filename: apache-maven-3.2.1-bin.tar.gz
            target_directory: apache-maven-3.2.1
            url: __DOWNLOAD_URL__
            checksum: md5:aaef971206104e04e21a3b580d9634fe

        3.3.9:
            target_filename: apache-maven-3.3.9-bin.tar.gz
            target_directory: apache-maven-3.3.9
            url: __DOWNLOAD_URL__
            checksum: md5:516923b3955b6035ba6b0a5b031fbd8b

tomcat:
    distributions:
        7.0.53:
            target_filename: apache-tomcat-7.0.53.tar.gz
            target_directory: apache-tomcat-7.0.53
            url: __DOWNLOAD_URL__
            checksum: md5:7062e134b4390e2ce6b54081aab26e3c

remote:
    client_hostname: "{{ powo_user }}"
