- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"

- include: python-package.yml

- name: libaugeas install
  package: pkg={{ item }}
  with_items: "{{ packages.augeas }}"
